In [1]:
import numpy as np

In [3]:
#Vectorization: it means apply operation on whole array instead 
#of single element...
#Operation like addition , division etc
#operation can be executed in parallel on multiple elements of the array

In [4]:
#Addition
#SUbstraction
#Multiplication
#Division
#Expoentiation
#Specific functions to perform them

# Arithmetic Operations

In [6]:
a = np.arange(1,11)
b = np.arange(21,31)
print("A:",a)
print("B:",b)

A: [ 1  2  3  4  5  6  7  8  9 10]
B: [21 22 23 24 25 26 27 28 29 30]


In [7]:
c = a+b
c

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [8]:
b-a

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [9]:
a*b

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [10]:
b/a

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [12]:
c = np.arange(2,12)

In [13]:
a**c

array([         1,          8,         81,       1024,      15625,
           279936,    5764801,  134217728, -808182895, 1215752192],
      dtype=int32)

In [14]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [15]:
np.add(a,b)

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [17]:
np.subtract(b,a)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [18]:
np.multiply(a,b)

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [20]:
np.divide(b,a)

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [21]:
np.mod(b,a)

array([0, 0, 2, 0, 0, 2, 6, 4, 2, 0], dtype=int32)

In [22]:
np.power(a,c)

array([         1,          8,         81,       1024,      15625,
           279936,    5764801,  134217728, -808182895, 1215752192],
      dtype=int32)

In [23]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

# BroadCasting

The term broadcating decribes how NumPy treats arrays with different shapes during arithmetic operations.
Subject to certain constraints, the smaller array is broadcast across the larger array so that they have compatible shapes...

In [30]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
b = np.arange(1,4)
b

array([1, 2, 3])

In [32]:
a+b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [33]:
c = np.array([1,2])
c

array([1, 2])

In [34]:
a+c

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [35]:
d = np.arange(24).reshape(2,3,4)
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [36]:
d.ndim

3

In [37]:
e = np.arange(4)
e

array([0, 1, 2, 3])

In [38]:
d-e

array([[[ 0,  0,  0,  0],
        [ 4,  4,  4,  4],
        [ 8,  8,  8,  8]],

       [[12, 12, 12, 12],
        [16, 16, 16, 16],
        [20, 20, 20, 20]]])

# Aggregate Function

In [39]:
first_arr = np.arange(10,110,10)
first_arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [40]:
second_arr = np.arange(10,100,10).reshape(3,3)
second_arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [41]:
second_arr.ndim

2

In [42]:
third_arr = np.arange(10,110,10).reshape(2,5)
third_arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [43]:
first_arr.sum()

550

In [44]:
second_arr.sum()

450

In [45]:
third_arr.sum()

550

In [69]:
second_arr

array([[ 1,  1,  2,  1],
       [ 3,  2,  3,  4],
       [ 4, 56,  7,  9],
       [ 4,  5,  6,  7]])

In [46]:
#For sum of rows
second_arr.sum(axis=0)

array([120, 150, 180])

In [48]:
#For sum of cols
second_arr.sum(axis=1)

array([ 60, 150, 240])

In [50]:
first_arr.prod()

1704722432

In [52]:
second_arr.prod()

-1786839040

In [53]:
third_arr.prod()

1704722432

In [54]:
third_arr.prod(axis = 0)

array([ 600, 1400, 2400, 3600, 5000])

In [55]:
#Average
np.average(third_arr)

55.0

In [56]:
#Min and max
np.min(third_arr)

10

In [57]:
np.max(third_arr)

100

In [58]:
np.mean(third_arr)

55.0

In [59]:
np.std(third_arr)

28.722813232690143

# Unique items and counts

In [61]:
first_arr = np.array([1,2,3,4,5,6,1,2,3,7,8,9,10])
first_arr

array([ 1,  2,  3,  4,  5,  6,  1,  2,  3,  7,  8,  9, 10])

In [62]:
np.unique(first_arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
second_arr = np.array([[1,1,2,1],[3,2,3,4],[4,56,7,9],[4,5,6,7]])

In [65]:
second_arr

array([[ 1,  1,  2,  1],
       [ 3,  2,  3,  4],
       [ 4, 56,  7,  9],
       [ 4,  5,  6,  7]])

In [66]:
np.unique(second_arr)

array([ 1,  2,  3,  4,  5,  6,  7,  9, 56])

In [67]:
np.unique(second_arr,axis=0)

array([[ 1,  1,  2,  1],
       [ 3,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 4, 56,  7,  9]])

In [ ]:
#index positions of unique values/elements


In [71]:
np.unique(first_arr,return_index=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 0,  1,  2,  3,  4,  5,  9, 10, 11, 12], dtype=int64))

In [73]:
#it will returns counts of unique elemnts
np.unique(second_arr,return_counts=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  9, 56]),
 array([3, 2, 2, 3, 1, 1, 2, 1, 1], dtype=int64))

# Transpose like operations

In [79]:
first_2darr = np.arange(12).reshape(3,4)
first_2darr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
first_2darr.shape

(3, 4)

In [82]:
arr = np.transpose(first_2darr)

In [83]:
arr.shape

(4, 3)

In [84]:
first3darr = np.arange(24).reshape(2,3,4)
first3darr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [87]:
np.moveaxis(first3darr,0,-1)

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [89]:
#Swapaxes
np.swapaxes(first3darr,0,2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

# Reversing an array

In [90]:
array_1dim = np.array([10,1,9,3,8,6,7,9,4,3,5,7])
array_1dim

array([10,  1,  9,  3,  8,  6,  7,  9,  4,  3,  5,  7])

In [91]:
array_1dim[::-1]

array([ 7,  5,  3,  4,  9,  7,  6,  8,  3,  9,  1, 10])

In [92]:
np.flip(array_1dim)

array([ 7,  5,  3,  4,  9,  7,  6,  8,  3,  9,  1, 10])

In [93]:
arr_2dim = np.arange(9).reshape(3,3)
arr_2dim

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
np.flip(arr_2dim)

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [95]:
np.flip(arr_2dim,1)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])