In [1]:
import numpy as np

In [2]:
twodim_arr = np.reshape(np.arange(12),(3,4))
twodim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
print(twodim_arr[1,1])
print(twodim_arr.shape)
twodim_arr.ndim

5
(3, 4)


2

In [4]:
twodim_arr[1]

array([4, 5, 6, 7])

In [6]:
threedim_arr = np.reshape(np.arange(3*4*5),(3,4,5))

In [7]:
threedim_arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [8]:
threedim_arr[0,2,3]

13

In [9]:
threedim_arr[2,-1,-1]

59

In [10]:
onedim_arr = np.arange(10)
onedim_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
onedim_arr[2:6]

array([2, 3, 4, 5])

In [13]:
onedim_arr[:5]

array([0, 1, 2, 3, 4])

In [15]:
onedim_arr[-3:]

array([7, 8, 9])

In [16]:
onedim_arr[::2]

array([0, 2, 4, 6, 8])

# Slicing  2D array

In [21]:
twodim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
twodim_arr[1:,0:2]

array([[4, 5],
       [8, 9]])

In [33]:
twodim_arr[:,2]

array([ 2,  6, 10])