In [1]:
import numpy as np

# Functions for joining Arrays

 -> concatenate
 -> stack
 -> hstack
 -> vstack

In [2]:
first_arr = np.arange(1,11)
second_arr = np.arange(11,21)
print(first_arr)
print(second_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [4]:
con_arr = np.concatenate((first_arr,second_arr))
con_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [11]:
third_2d_arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
third_2d_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
fourth_2d_arr = np.array([[11,12,13,14,15],[16,17,18,19,20]])
fourth_2d_arr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [15]:
cont2d_arr = np.concatenate((third_2d_arr,fourth_2d_arr),axis=1)

In [17]:
cont2d_arr

array([[ 1,  2,  3,  4, 11, 12, 13, 14, 15],
       [ 5,  6,  7,  8, 16, 17, 18, 19, 20]])

In [18]:
st_arr = np.stack((first_arr,second_arr))
st_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [21]:
hat_arr = np.hstack((first_arr,second_arr))
hat_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
vst_arr = np.vstack((first_arr,second_arr))
vst_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

# Splitting Arrays

In [23]:
#split
#array_split
#hsplit
#vsplit

In [24]:
fifth_arr = np.arange(1,13)
fifth_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
sp_arr = np.array_split(fifth_arr,4)
sp_arr

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [28]:
sp_arr[2]

array([7, 8, 9])

In [29]:
sp_array = np.array_split(fifth_arr,8)
sp_array

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([9]),
 array([10]),
 array([11]),
 array([12])]

In [31]:
third_2d_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
hs_arr = np.hsplit(third_2d_arr,4)
hs_arr

[array([[1],
        [5]]),
 array([[2],
        [6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

In [38]:
vs_arr = np.vsplit(third_2d_arr,2)
print(vs_arr)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
