In [3]:
import math
radius = float(input("Enter radius of a sphere:"))
volume= (4/3) * math.pi *pow(radius,3)
print("Volume of the sphere will be  %.2f" %volume)

Enter radius of a sphere:2
Volume of the sphere will be  33.51


In [7]:
number_1 = float(input("Enter Number 1:"))
number_2 = float(input("Enter Number 2:"))
add = number_1 + number_2
sub = number_1 - number_2
div = number_1 / number_2
mul = number_1 * number_2

print("Add = ",add)
print("Sub = ",sub)
print("Div = ",div)
print("Mul = ",mul)

Enter Number 1:2
Enter Number 2:2
Add =  4.0
Sub =  0.0
Div =  1.0
Mul =  4.0


In [8]:
temp = float(input("Enter the temperature in Celsius:"))
temp_in_fahrenheit = (temp * (9 / 5)) + 32
print("Temperature in Fahrenheit is ",temp_in_fahrenheit)


Enter the temperature in Celsius:37
Temperature in Fahrenheit is  98.60000000000001


In [3]:
####Importing numpy module

import numpy as np


In [4]:
integer = np.array([10,20,30,40,50])
print(integer)

[10 20 30 40 50]


In [8]:
integer[2]

30

In [10]:
integer[0] = 20
integer[0]

20

In [11]:
#Decimal number will be turancating the number because
#numpy array store same data type elements


integer[0] = 29.5
integer[0]

29

In [12]:
#we can check data type of numpy array like this

integer.dtype

dtype('int32')

In [16]:
smallInt = np.array(integer,dtype = np.int8)
smallInt


array([29, 20, 30, 40, 50], dtype=int8)

In [18]:
smallInt.dtype


dtype('int8')

In [24]:
#For checking array size 

print("Intger array size: {}".format(integer.nbytes))
print("Small array size: {}".format(smallInt.nbytes))

Intger array size: 20
Small array size: 5


In [27]:
floatArray = np.array([1.1,2.3,4.5,5.6])
floatArray.dtype

dtype('float64')

In [32]:
#Multidimensional Array...
array2D = np.array([[1,2,3,4,5],[6,7,8,9,10]])
array2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [33]:
array2D[0,0]

1

In [34]:
array2D[1,4]

10

In [35]:
#for checking array dimensions
array2D.ndim

2

In [60]:
#3 dimensions array

multi_dimen = np.array([[[1,2,3],[4,5,6],[5,6,7]],[[1,2,3],[4,5,6],[5,6,7]]])

In [61]:
multi_dimen

array([[[1, 2, 3],
        [4, 5, 6],
        [5, 6, 7]],

       [[1, 2, 3],
        [4, 5, 6],
        [5, 6, 7]]])

In [63]:
multi_dimen.ndim


#Similary we can create 4 dim and upto so on....

3

# Creating arrays from lists and other Python strucutre

In [64]:
first_list = [1,2,3,4,5,6,7,8,9,10]
first_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [67]:
first_array = np.array(first_list)
first_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
first_array.nbytes

40

In [70]:
second_list = [1,2,3,-1.23,50,12800,4.56]

In [72]:
second_array = np.array(second_list)
second_list

[1, 2, 3, -1.23, 50, 12800, 4.56]

In [74]:
second_array.dtype

dtype('float64')

In [75]:
third_list = [123,'Umar',234,'Ali']
third_list

[123, 'Umar', 234, 'Ali']

In [77]:
third_array = np.array(third_list)
third_array

array(['123', 'Umar', '234', 'Ali'], dtype='<U11')

In [78]:
third_array.dtype

dtype('<U11')

In [79]:
#creating lists from tuples
tuple_01 = (1,2,3,4,5)
array_from_tuple = np.array(tuple_01)

In [80]:
array_from_tuple

array([1, 2, 3, 4, 5])

In [81]:
array_from_tuple.dtype

dtype('int32')

In [82]:
###creating array from list of lists
multiDimList = np.array([[[1,2,3],[4,5,6],[5,6,7]],[[1,2,3],[4,5,6],[5,6,7]]])
multiDimList

array([[[1, 2, 3],
        [4, 5, 6],
        [5, 6, 7]],

       [[1, 2, 3],
        [4, 5, 6],
        [5, 6, 7]]])

In [83]:
array_from_multiDimList = np.array(multiDimList)

In [84]:
array_from_multiDimList


array([[[1, 2, 3],
        [4, 5, 6],
        [5, 6, 7]],

       [[1, 2, 3],
        [4, 5, 6],
        [5, 6, 7]]])

In [88]:
array_from_multiDimList.dtype

dtype('int32')

# Intrisic NumpY array creation

In [91]:
integers_array = np.arange(10)
integers_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
second_array = np.arange(100,130)
new_array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

In [94]:
third_array = np.arange(1,20,2)
third_array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [95]:
#for generating array of floating numbers
#we will use linspace function

In [98]:
frist_float_arrray = np.linspace(10,20)
#by default it generate 50 sets
frist_float_arrray

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [99]:
second_float_array = np.linspace(1,10,5)
second_float_array

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [100]:
#Array  of random numbers within given range

In [101]:
first_rand_arr = np.random.rand(10)
first_rand_arr

array([0.28340439, 0.60373475, 0.40746129, 0.16906717, 0.41435595,
       0.88700979, 0.53145215, 0.29051312, 0.28146195, 0.09832402])

In [102]:
second_rand_arr = np.random.rand(4,4)
second_rand_arr

array([[0.19285462, 0.29497103, 0.28429776, 0.72657427],
       [0.74724927, 0.42972641, 0.79689073, 0.17409266],
       [0.49279539, 0.49595439, 0.68404147, 0.34470862],
       [0.41357361, 0.86252723, 0.13998805, 0.82786921]])