# Adding, Removing and sorting elements

In [1]:
import numpy as np

In [7]:
first_arr = np.array([1,2,3,5])
first_arr

array([1, 2, 3, 5])

In [11]:
first_arr_new = np.insert(first_arr,3,4)
first_arr_new

array([1, 2, 3, 4, 5])

In [12]:
second_arr = np.array([1,2,3,4])
second_arr

array([1, 2, 3, 4])

In [15]:
new_second_arr = np.append(second_arr,5)
new_second_arr

array([1, 2, 3, 4, 5])

In [16]:
third_arr = np.array([1,2,3,5,6,4])
third_arr

array([1, 2, 3, 5, 6, 4])

In [17]:
del_arr = np.delete(third_arr,4)
del_arr

array([1, 2, 3, 5, 4])

In [22]:
one_dim_arr = np.random.randint(0,20,20)
one_dim_arr

array([ 0, 18, 10, 14, 15,  4, 19,  6,  2,  0,  8,  7, 19, 10,  9, 12,  0,
       13, 13, 11])

In [23]:
one_dim_arr.shape

(20,)

In [24]:
int_two_dim_arr = np.array([[3,4,5,6,7],[3,6,8,9,0]])

In [26]:
int_two_dim_arr.ndim

2

In [27]:
print(np.sort(one_dim_arr))

[ 0  0  0  2  4  6  7  8  9 10 10 11 12 13 13 14 15 18 19 19]


In [28]:
print(np.sort(int_two_dim_arr))

[[3 4 5 6 7]
 [0 3 6 8 9]]


In [ ]:
string_arr = np.array(['Orange','Yellow','Red','white'])