# Adding, Removing and sorting elements

In [1]:
import numpy as np

In [7]:
first_arr = np.array([1,2,3,5])
first_arr

array([1, 2, 3, 5])

In [11]:
first_arr_new = np.insert(first_arr,3,4)
first_arr_new

array([1, 2, 3, 4, 5])

In [12]:
second_arr = np.array([1,2,3,4])
second_arr

array([1, 2, 3, 4])

In [15]:
new_second_arr = np.append(second_arr,5)
new_second_arr

array([1, 2, 3, 4, 5])

In [16]:
third_arr = np.array([1,2,3,5,6,4])
third_arr

array([1, 2, 3, 5, 6, 4])

In [17]:
del_arr = np.delete(third_arr,4)
del_arr

array([1, 2, 3, 5, 4])

In [22]:
one_dim_arr = np.random.randint(0,20,20)
one_dim_arr

array([ 0, 18, 10, 14, 15,  4, 19,  6,  2,  0,  8,  7, 19, 10,  9, 12,  0,
       13, 13, 11])

In [23]:
one_dim_arr.shape

(20,)

In [24]:
int_two_dim_arr = np.array([[3,4,5,6,7],[3,6,8,9,0]])

In [26]:
int_two_dim_arr.ndim

2

In [27]:
print(np.sort(one_dim_arr))

[ 0  0  0  2  4  6  7  8  9 10 10 11 12 13 13 14 15 18 19 19]


In [28]:
print(np.sort(int_two_dim_arr))

[[3 4 5 6 7]
 [0 3 6 8 9]]


In [29]:
string_arr = np.array(['Orange','Yellow','Red','White','Black'])
string_arr

array(['Orange', 'Yellow', 'Red', 'White', 'Black'], dtype='<U6')

In [30]:
print(np.sort(string_arr))

['Black' 'Orange' 'Red' 'White' 'Yellow']


# Copies and Views

Some functions returns copies and some returns views..
Copy is the new array and view is the different view of the original array...
Copy is stored in different location but view is the ref to the same memory...

In [31]:
s_ids_numbers = np.array([1111,1212,1313,1414,1515,1616,1717,1818])

In [32]:
s_ids_numbers

array([1111, 1212, 1313, 1414, 1515, 1616, 1717, 1818])

In [33]:
s_ids_numbers_reg = s_ids_numbers

In [34]:
print("Id of s_ids_numbers",id(s_ids_numbers))
print("Id of s_ids_numbers_reg",id(s_ids_numbers_reg))

Id of s_ids_numbers 2826582928144
Id of s_ids_numbers_reg 2826582928144


In [36]:
s_ids_numbers_reg[1] = 2222
print(s_ids_numbers)
print(s_ids_numbers_reg)

[1111 2222 1313 1414 1515 1616 1717 1818]
[1111 2222 1313 1414 1515 1616 1717 1818]


In [37]:
#Assignment don't makes copy of the array it uses ref
s_ids_numbers_reg_cp = s_ids_numbers.copy()

In [38]:
print(s_ids_numbers_reg_cp)

[1111 2222 1313 1414 1515 1616 1717 1818]


In [39]:
print(s_ids_numbers_reg_cp == s_ids_numbers)

[ True  True  True  True  True  True  True  True]


In [40]:
print("Id of s_ids_numbers_reg_cp",id(s_ids_numbers_reg_cp))
print("Id of s_ids_numbers",id(s_ids_numbers))

Id of s_ids_numbers_reg_cp 2826584420976
Id of s_ids_numbers 2826582928144


In [41]:
s_ids_numbers[0] = 1000
print('Original',s_ids_numbers)
print('Copy',s_ids_numbers_reg_cp)
#It is also called deep copy

Original [1000 2222 1313 1414 1515 1616 1717 1818]
Copy [1111 2222 1313 1414 1515 1616 1717 1818]


In [42]:
#Views
s_ids_numbers_v = s_ids_numbers.view()

In [43]:
s_ids_numbers_v[0] = 2000
print("Original:",s_ids_numbers)
print("View:",s_ids_numbers_v)

Original: [2000 2222 1313 1414 1515 1616 1717 1818]
View: [2000 2222 1313 1414 1515 1616 1717 1818]


In [44]:
print(s_ids_numbers_v.base)
print(s_ids_numbers.base)

[2000 2222 1313 1414 1515 1616 1717 1818]
None
