# Reshaping arrays

In [1]:
import numpy as np

In [2]:
one_dim_arr = np.arange(1,13)
one_dim_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
second_arr = np.reshape(one_dim_arr,(3,4))
second_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
third_arr = np.reshape(one_dim_arr,(6,2))
third_arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [9]:
fourth_arr = np.reshape(one_dim_arr,(4,4))

ValueError: cannot reshape array of size 12 into shape (4,4)

In [11]:
fifth_arr = np.reshape(one_dim_arr,(3,2,2))
print(fifth_arr)
print("Dimensions of fifth_arr:",fifth_arr.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Dimensions of fifth_arr: 3


In [12]:
sixth_arr = np.array([[1,2],[3,4],[5,6]])
sixth_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
seventh_arr = np.reshape(sixth_arr,-1)
seventh_arr
#this is known as flatten

array([1, 2, 3, 4, 5, 6])

np.ndarray.flatten this will create copy
numpy.ravel will create the view

In [16]:
eighth_arr_flat = sixth_arr.flatten()
print("eighth_arr_flat",eighth_arr_flat)
ninth_arr_rev = sixth_arr.ravel()
print("ninth_arr_rev",ninth_arr_rev)

eighth_arr_flat [1 2 3 4 5 6]
ninth_arr_rev [1 2 3 4 5 6]


In [17]:
eighth_arr_flat[0] = 100
ninth_arr_rev[0] = 200

In [18]:
print("eighth_arr_flat",eighth_arr_flat)
print("ninth_arr_rev",ninth_arr_rev)

eighth_arr_flat [100   2   3   4   5   6]
ninth_arr_rev [200   2   3   4   5   6]
